#!/bin/bash
# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

branch=`git symbolic-ref HEAD`
if [ "$branch" = "refs/heads/main" ] || [[ "$branch" == refs/heads/dev-v* ]]; then
    echo "Direct commits to the main and dev branches are not allowed."
    exit 1
fi

# Check lints
echo Formatting and running lints...
./lint.sh
if [ $? -eq 0 ]
then
  echo -e "Lint succeeded."
  exit 0
else
  ./format.sh
  echo -e "\n=======================================================" >&2
  echo -e "Lint failed. 'just fmt' was run automatically, add the changes and try again." >&2
  echo -e "=======================================================\n" >&2
  exit 1
fi
